In [ ]:
# Import library
import torch
# Check version
print(torch.__version__)

2.10.0+cpu


In [ ]:
# Check if a compatible NVIDIA GPU (CUDA) is accessible by PyTorch
if torch.cuda.is_available():
  print("GPU is available!")

  # Get and print the actual hardware name of the first GPU (index 0)
  print(f"Using GPU : {torch.cuda.get_device_name(0)}")
else:
  # If no GPU is found, fall back to the standard processor (CPU)
  print("GPU not available. Using CPU.")

GPU not available. Using CPU.


#### Creating Tensor..

In [ ]:
# Using empty
# Creates a 2*3 tensor (2 rows, 3 columns) but does not initialize the memory.
# It will contain whatever random "garbage" values were already sitting in your Computer's RAM.
a = torch.empty(2,3)
print(a)

tensor([[-7.8215e+31,  4.4177e-41, -7.8215e+31],
        [ 4.4177e-41, -7.8214e+31,  4.4177e-41]])


In [ ]:
# Check type
# The type() function checks the python class/data structure of the variable "a".
type(a)

torch.Tensor

In [ ]:
# Using zeros
# Creates a 2*3 tensor (2 rows, 3 columns) completely filled with zeros (0.0)
# By default, PyTorch creates these zeros as float (decimal) numbers, not integers.
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# Using ones
# Creates a 2*3 tensor completely filled with ones(1.0)
# By default, PyTorch creates these ones as float (decimal) numbers, not integers.
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# Using rand
# Creates a 4*3 tensor (4 rows and 3 columns) filled with random decimal numbers.
# The numbers are chosen from a "uniform distribution" between 0.0 and 1.0.
# It return a float data type.
torch.rand(4,3)

tensor([[0.6129, 0.4378, 0.5773],
        [0.8043, 0.9302, 0.9960],
        [0.8672, 0.5800, 0.0677],
        [0.4607, 0.2150, 0.8999]])

In [ ]:
# Using manual_seed
# Lock the random number generator with a specific "key" or seed (e.g., 500)
torch.manual_seed(500)

# Generates a 2*3 tensor of random decimal numbers.
# Because of the seed, these specific numbers will NEVER changes upon rerunning.
torch.rand(2,3)

tensor([[0.5820, 0.1338, 0.7995],
        [0.3071, 0.6526, 0.6105]])

In [ ]:
# Using tensor
# Converts a standard Python list of lists into a PyTorch Tensor.
# Since we provided integers (1,2,3..), PyTorch automatically infers the type as int64.
t = torch.tensor([[1,2,3],[4,5,6]])
print(t)
print("Datatype:",t.dtype)

tensor([[1, 2, 3],
        [4, 5, 6]])
Datatype: torch.int64


In [ ]:
# Using arange
# Create a sequence from start (0) to end (10, exclusive) with a step size (2).
a = torch.arange(0,10,2)
print("Using arange ->",a)

Using arange -> tensor([0, 2, 4, 6, 8])


In [ ]:
# Using linspace
# Creates "7" equally spaced points between start (0) and end (10, inclusive).
l = torch.linspace(0,10,7)
print("Using linspace ->", l)

Using linspace -> tensor([ 0.0000,  1.6667,  3.3333,  5.0000,  6.6667,  8.3333, 10.0000])


In [ ]:
# Using eye
# Create a 2D Identity matrix (1s on the diagonal, 0s elsewhere) of size 5*5
e = torch.eye(5)
print("Using eye ->", e)

Using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [ ]:
# Using full
# Creates a 3*3 matrix and fills EVERY position with the number "5".
f = torch.full((3,3),5)
print("Using full ->", f)

Using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#### Tensor Shapes..

In [ ]:
# Using tensor
# Converts a standard Python list of lists into a PyTorch Tensor.
x = torch.tensor([[7,2,3],[4,5,6]])
x

tensor([[7, 2, 3],
        [4, 5, 6]])

In [ ]:
# Using shape
# Checking the shape (dimension) of the tensor.
x.shape

torch.Size([2, 3])

In [ ]:
# Using empty_like()
# Creates a new tensor with the EXACT same shape and datatype as "x"
# But just like normal empty(), it leaves the memory uninitialized (fills with garbage values).
torch.empty_like(x)

tensor([[                  0, 7310593858020254331, 3616445622929465956],
        [6068654568117382454, 3833471699382841394, 6500441614764554030]])

In [ ]:
# Using zeros_like()
# Creates a new tensor with the EXACT SAME shape and datatype as 'x'.
# Step 1: Allocates the exact same memory space as 'x'.
# Step 2: Manually fills that entire space with 0s (0.0).
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
# Using ones_like()
# Creates a new tensor with the EXACT same shape and datatype as "x".
# Step 1: Allocates the exact same memory space as "x".
# Step 2: Manually fills that entire space with 1s.
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# Using rand_like()
# Step 1: Copies the SHAPE of "x" (2*2).
# Step 2: Fills the space with random decimal numbers between 0.0 and 0.1.
# Step 3: Forces the new tensor to be float 32, IGNORING x's original integer datatype.
torch.rand_like(x, dtype = torch.float32)

tensor([[0.1575, 0.6983, 0.7883],
        [0.7981, 0.4593, 0.8997]])

#### Tensor Data Types..

In [ ]:
# It will tell us the data type of x.
x.dtype

torch.int64

In [ ]:
# Step 1: We give decimal numbers (1.0, 2.0, 3.0) in the list.
# Step 2: We forcefully tell pytorch to make them integers (int32).
# Step 3: Pytorch cuts the decimal parts and saves them as pure integers.
x = torch.tensor([1.0,2.0,3.0], dtype = torch.int32)
print(x)
print(x.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.int32


In [ ]:
# Step 1: We give integer numbers (1, 2, 3) in the list.
# Step 2: We forcefully tell PyTorch to make them decimal values (float64).
# Step 3: PyTorch add decimal after a integer numbers.
torch.tensor([1, 2, 3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# We use the magic wand .to() to change it to Float
x.to(torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

#### Mathematical Operations..

1. Scaller Operation:-

In [ ]:
# Create a tensor (2,2)
x = torch.rand(2,2)
x

tensor([[0.2518, 0.5648],
        [0.0302, 0.5930]])

In [ ]:
# Addition
a = x+2

# Substraction
b = x-2

# Multiplication
c = x*3

# Division
d = x / 3

# Int Division
e = (x*100)//3

# Modulas Division
f = ((x*100)//3)%2

# Power
g = x**2

In [ ]:
print("Original Tensor:")
print(x)
print("*"*40)
print("Addition:")
print(a)
print("*"*40)
print("Substraction:")
print(b)
print("*"*40)
print("Multiplication:")
print(c)
print("*"*40)
print("Division:")
print(d)
print("*"*40)
print("Int Division:")
print(e)
print("*"*40)
print("Modulas Division:")
print(f)
print("*"*40)
print("Power:")
print(g)

Original Tensor:
tensor([[0.2518, 0.5648],
        [0.0302, 0.5930]])
****************************************
Addition:
tensor([[2.2518, 2.5648],
        [2.0302, 2.5930]])
****************************************
Substraction:
tensor([[-1.7482, -1.4352],
        [-1.9698, -1.4070]])
****************************************
Multiplication:
tensor([[0.7555, 1.6943],
        [0.0905, 1.7790]])
****************************************
Division:
tensor([[0.0839, 0.1883],
        [0.0101, 0.1977]])
****************************************
Int Division:
tensor([[ 8., 18.],
        [ 1., 19.]])
****************************************
Modulas Division:
tensor([[0., 0.],
        [1., 1.]])
****************************************
Power:
tensor([[0.0634, 0.3190],
        [0.0009, 0.3517]])


2. Element Wise Operation:-

In [ ]:
# Create tensor
a = torch.rand(2,3)
b = torch.rand(2,3)

In [ ]:
print(a)
print(b)

tensor([[0.6386, 0.4795, 0.6030],
        [0.7351, 0.7602, 0.8872]])
tensor([[0.8153, 0.2794, 0.0168],
        [0.6273, 0.6037, 0.1817]])


In [ ]:
# Addition
u = a + b

# Substraction
v = a - b

# Multiplication
w = a * b

# Division
x = a / b

# Modulas Division
y = a % b

# Power
z = a**b

In [ ]:
print(f"\nOriginal Tensor:\n")
print(a)
print(b)
print("*"*40)
print(f"\nAddition:\n")
print(u)
print("*"*40)
print(f"\nSubstraction:\n")
print(v)
print("*"*40)
print("\nMultiplication:\n")
print(w)
print("*"*40)
print("\nDivision:\n")
print(x)
print("*"*40)
print("\nModulas Division:\n")
print(y)
print("*"*40)
print("\nPower:\n")
print(z)


Original Tensor:

tensor([[0.6386, 0.4795, 0.6030],
        [0.7351, 0.7602, 0.8872]])
tensor([[0.8153, 0.2794, 0.0168],
        [0.6273, 0.6037, 0.1817]])
****************************************

Addition:

tensor([[1.4540, 0.7589, 0.6199],
        [1.3624, 1.3639, 1.0689]])
****************************************

Substraction:

tensor([[-0.1767,  0.2001,  0.5862],
        [ 0.1079,  0.1565,  0.7055]])
****************************************

Multiplication:

tensor([[0.5207, 0.1340, 0.0102],
        [0.4611, 0.4589, 0.1612]])
****************************************

Division:

tensor([[ 0.7833,  1.7165, 35.8074],
        [ 1.1720,  1.2593,  4.8819]])
****************************************

Modulas Division:

tensor([[0.6386, 0.2001, 0.0136],
        [0.1079, 0.1565, 0.1603]])
****************************************

Power:

tensor([[0.6938, 0.8144, 0.9915],
        [0.8245, 0.8475, 0.9785]])


In [ ]:
# Tensor
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# Use torch.abs() to remove all minus signs (Only negative values into positive value)
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# Use torch.neg() to flip the signs of all numbers (positive into negative and negative into positive)
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
# Tensor
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# Use torch.round() to find the nearest whole number (like 3.2 = 3 & 3.8 = 4)
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# Use torch.ceil() to push all numbers UP to the next whole number (like 3.1 = 4 & 3.2 = 4)
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# Use torch.floor() to push all numbers DOWN to the previous whole number (like 3.9 = 3 & 3.8 = 3)
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# Use torch.clamp() to force all numbers strictly between 2.0 and 3.0
torch.clamp(d, min = 2, max = 3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

- **If the number is less than the Minimum:** It forcefully pulls it up to make it equal to the min (2).

- **If the number is greater than the Maximum:** It forcefully cuts it down (caps it) to make it equal to the max (3).

- **If the number is between the limits:** It leaves the number completely untouched (the safe zone).

3. Reduction Operation:-

In [ ]:
# Tensor
# Step 1: Create a 2x3 matrix.
# Step 2: Fill it with random integers from 0 to 9.
# Step 3: Forcefully convert those integers into floats (add .0 at the end).
e = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)
e

tensor([[3., 3., 2.],
        [1., 9., 8.]])

In [ ]:
# Add numbers top-to-bottom (Column-wise sum)
# It crushes 2 rows into 1 single row
torch.sum(e, dim=0)

tensor([ 4., 12., 10.])

- **dim=0:** This crushes the matrix from Top to Bottom (Vertically). This means it adds the numbers column-wise and crushes all the rows together to form just 1 single line (Row).

- **dim=1:** This crushes the matrix from Left to Right (Horizontally). (This adds the numbers row-wise).

In [ ]:
# Add ALL numbers together (No dimension specified)
# It crushes the entire matrix into a single scalar value
torch.sum(e)

tensor(26.)

In [ ]:
# Calculate the average of ALL numbers in the matrix
# It divides the total sum by the total number of items
torch.mean(e)

tensor(4.3333)

In [ ]:
# Calculate the average vertically (Top to Bottom)
# It crushes the 2 rows into 1 row of averages
torch.mean(e, dim=0)

tensor([2., 6., 5.])

In [ ]:
# Find the middle-most value of the entire matrix
# First it flattens and sorts: [0., 1., 3., 5., 8., 9.]
# Then it picks the middle value (if two values in middle then pick up the small value)
torch.median(e)

tensor(3.)

In [ ]:
# Find the smallest number in the entire matrix
# It checks every element and picks the lowest one
torch.min(e)

tensor(1.)

In [ ]:
# Find the largest number in the entire matrix
# It checks every element and picks the highest one
torch.max(e)

tensor(9.)

In [ ]:
# Multiply ALL numbers inside the matrix together
torch.prod(e)

tensor(1296.)

In [ ]:
# Calculate the Standard Deviation of all numbers
# It tells us how spread out the numbers are from the mean
torch.std(e)

tensor(3.3267)

In [ ]:
# Calculate the Variance of all numbers
# It tells us the squared spread of numbers from the mean
torch.var(e)

tensor(11.0667)

In [ ]:
# Find the position (index) of the largest number
torch.argmax(e)

tensor(4)

4. Matrix Operations:-

In [ ]:
# Tensor
f = torch.randint(size = (2,3), low = 0, high = 10)
g = torch.randint(size = (3,2), low = 0, high = 10)

print(f)
print(g)

tensor([[3, 6, 2],
        [4, 1, 2]])
tensor([[5, 5],
        [2, 1],
        [9, 1]])


In [ ]:
# Perform core Matrix Multiplication
# Resulting shape will be (2x3) @ (3x2) = (2x2)
# (m*n) & (n*p) = (m*p)
torch.matmul(f,g)

tensor([[45, 23],
        [40, 23]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

print(vector1)
print(vector2)

tensor([1, 2])
tensor([3, 4])


In [ ]:
# Compute the dot product (1D tensor is compulsory) vector
# (1*4) + (2*5) + (3*6) = 32.0
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# Swap Dimension 0 (Rows) and Dimension 1 (Columns)
# This converts the 2x3 matrix into a 3x2 matrix
torch.transpose(f, 0, 1)

tensor([[3, 4],
        [6, 1],
        [2, 2]])

In [ ]:
# Tensor
h = torch.randint(size = (3,3), low = 0, high = 10, dtype = torch.float32)
h

tensor([[9., 2., 5.],
        [3., 4., 1.],
        [9., 6., 2.]])

In [ ]:
# Calculate the Determinant (It must be a float type and (n*n) shape tensor)
# Formula: (4*3) - (2*1) = 12 - 2 = 10
torch.det(h)

tensor(-66.)

In [ ]:
# Calculate the Inverse Matrix (h^-1)
# It must be a det != 0 and (n*n) shape tensor
torch.inverse(h)

tensor([[-0.0303, -0.3939,  0.2727],
        [-0.0455,  0.4091, -0.0909],
        [ 0.2727,  0.5455, -0.4545]])

5. Comparision Operations:-

In [ ]:
# Tensor
i = torch.randint(size = (2,3), low = 0, high = 10)
j = torch.randint(size = (2,3), low = 0, high = 10)

print(i)
print(j)

tensor([[8, 7, 1],
        [2, 8, 2]])
tensor([[3, 0, 8],
        [0, 4, 2]])


In [ ]:
# Greater than
a = i > j

# Less than
b = i < j

# Equal to
c = i == j

# Not Equal to
d = i != j

# Greater than equal to
e = i >= j

# Less than equal to
f = i <= j

In [ ]:
print("Greater than:")
print(a)
print("*"*40)
print("Less than:")
print(b)
print("*"*40)
print("Equal to:")
print(c)
print("*"*40)
print("Not equal to:")
print(d)
print("*"*40)
print("Greater than equal to:")
print(e)
print("*"*40)
print("Less than equal to:")
print(f)

Greater than:
tensor([[ True,  True, False],
        [ True,  True, False]])
****************************************
Less than:
tensor([[False, False,  True],
        [False, False, False]])
****************************************
Equal to:
tensor([[False, False, False],
        [False, False,  True]])
****************************************
Not equal to:
tensor([[ True,  True,  True],
        [ True,  True, False]])
****************************************
Greater than equal to:
tensor([[ True,  True, False],
        [ True,  True,  True]])
****************************************
Less than equal to:
tensor([[False, False,  True],
        [False, False,  True]])


6. Special Functions:-

In [ ]:
# Tensor
k = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)
k

tensor([[1., 8., 6.],
        [0., 5., 2.]])

In [ ]:
# Calculate the Natural Logarithm element-wise
torch.log(k)

tensor([[0.0000, 2.0794, 1.7918],
        [  -inf, 1.6094, 0.6931]])

- **Strictly Positive Numbers:** The number you are calculating the logarithm for must be greater than zero ($> 0$).
- **If the number is 1:** The answer will always be 0.0 (because $\ln(1) = 0$).
- **If the number is exactly $e$ (2.718):** The answer will be exactly 1.0.
- **If the number is 0:** PyTorch will get upset and return -inf (Negative Infinity).
- **If the number is negative (e.g., -5):** PyTorch will return nan (Not a Number), because the logarithm of negative numbers does not exist.

In [ ]:
# Calculate the Exponential element-wise (e^x)
# It will undo the log and bring back our original numbers!
torch.exp(k)

tensor([[2.7183e+00, 2.9810e+03, 4.0343e+02],
        [1.0000e+00, 1.4841e+02, 7.3891e+00]])

- **If the number is 0.0:** The answer will always be 1.0 (because $e^0 = 1$).
- **If the number is 1.0:** The answer will be exactly 2.718 ($e$) (because $e^1 = e$).
- **Undoing Log:** If you first apply log to a number, and then apply exp to the result, you will get the exact original number back! ($e^{\ln(x)} = x$).
- **Always a Positive Answer:** Whether the number inside tensor k is negative or positive, the final answer of torch.exp(k) will always be greater than zero (Positive).

In [ ]:
# Calculate the Square Root element-wise
# 4.0 becomes 2.0, 9.0 becomes 3.0, and -9.0 becomes 'nan'
torch.sqrt(k)

tensor([[1.0000, 2.8284, 2.4495],
        [0.0000, 2.2361, 1.4142]])

In [ ]:
# Apply the Sigmoid function
# It will squash all these numbers strictly between 0.0 and 1.0
torch.sigmoid(k)

tensor([[0.7311, 0.9997, 0.9975],
        [0.5000, 0.9933, 0.8808]])

- **Large Positive Number:** If the number is much greater than zero (e.g., 10.0 or 100.0), the answer will be squashed very close to 1.0 (e.g., 0.999).

- **Large Negative Number:** If the number is highly negative (e.g., -10.0 or -500.0), the answer will be pushed very close to 0.0 (e.g., 0.0001).

- **Exactly Zero (0.0):** If the number is exactly 0.0, the Sigmoid function will set it to the exact center, which is 0.5.

In [ ]:
# Apply Softmax along dimension 0
# It converts the scores into probabilities that sum up to 1.0
torch.softmax(k, dim=0)

tensor([[0.7311, 0.9526, 0.9820],
        [0.2689, 0.0474, 0.0180]])

#### Inplace Operations..

In [ ]:
# Tensor
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.9189, 0.5979, 0.9951],
        [0.5987, 0.3359, 0.3365]])
tensor([[0.5628, 0.7409, 0.2640],
        [0.8127, 0.8248, 0.3056]])


In [ ]:
# x.add_(y), x.mul_(y), x.sub_(y).. etc;
# It does NOT create a new tensor. It directly attacks and changes 'm'
m.add_(n)

tensor([[1.4817, 1.3387, 1.2591],
        [1.4115, 1.1608, 0.6421]])

In [ ]:
m

tensor([[1.4817, 1.3387, 1.2591],
        [1.4115, 1.1608, 0.6421]])

In [ ]:
n

tensor([[0.5628, 0.7409, 0.2640],
        [0.8127, 0.8248, 0.3056]])

In [ ]:
# Apply ReLU Activation Function but return a new variable. It not directly changes m
# All negatives become 0. All positives stay exactly the same.
torch.relu(m)

tensor([[1.4817, 1.3387, 1.2591],
        [1.4115, 1.1608, 0.6421]])

In [ ]:
# Apply In-place ReLU
# It does NOT return a new variable. It directly changes 'm'.
m.relu_()

tensor([[1.4817, 1.3387, 1.2591],
        [1.4115, 1.1608, 0.6421]])

In [ ]:
m

tensor([[1.4817, 1.3387, 1.2591],
        [1.4115, 1.1608, 0.6421]])

#### Copying a Tensor..

In [ ]:
# Tensor
a = torch.rand(2,3)
a

tensor([[0.0480, 0.9561, 0.1605],
        [0.6300, 0.4950, 0.6750]])

In [ ]:
# We assign 'b = a'
# Both 'a' and 'b' now point to the exact same memory location)
b = a
b

tensor([[0.0480, 0.9561, 0.1605],
        [0.6300, 0.4950, 0.6750]])

In [ ]:
# Modify the specific element at Row 0, Column 0 (Top-Left corner)
# This will overwrite the number with '0'
a[0][0] = 0
a

tensor([[0.0000, 0.9561, 0.1605],
        [0.6300, 0.4950, 0.6750]])

In [ ]:
b

tensor([[0.0000, 0.9561, 0.1605],
        [0.6300, 0.4950, 0.6750]])

In [ ]:
# Represents the exact memory address of a tensor (or any variable) within the computer's RAM.
id(a)

137957584968816

In [ ]:
# Represents the exact memory address of a tensor (or any variable) within the computer's RAM.
id(b)

137957584968816

In [ ]:
# Use .clone() to create a completely independent copy
b = a.clone()

- **If the id() of two variables is exactly the same:** It means they are not two separate pieces of data, but rather two different names pointing to the exact same data (Aliasing).

- **If you use .clone() or a standard math function (like add()):** The computer creates a completely new memory address, resulting in a completely new and different id().

In [ ]:
a

tensor([[0.0000, 0.9561, 0.1605],
        [0.6300, 0.4950, 0.6750]])

In [ ]:
b

tensor([[0.0000, 0.9561, 0.1605],
        [0.6300, 0.4950, 0.6750]])

In [ ]:
# Modify the specific element at Row 0, Column 0 (Top-Left corner)
# This will overwrite the number with '10'
a[0][0] = 10
a

tensor([[10.0000,  0.9561,  0.1605],
        [ 0.6300,  0.4950,  0.6750]])

In [ ]:
b

tensor([[0.0000, 0.9561, 0.1605],
        [0.6300, 0.4950, 0.6750]])

In [ ]:
# Represents the exact memory address of a tensor (or any variable) within the computer's RAM.
id(a)

137957584968816

In [ ]:
# Represents the exact memory address of a tensor (or any variable) within the computer's RAM.
id(b)

137957244606000

In [ ]:
# Tensor
a = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
a

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Check shape of the tensor
a.shape

torch.Size([3, 3])

In [ ]:
# .empty_like(x), ones_like(a), zeros_like(a)
b = torch.empty_like(a)